### ISSUE TITLE
invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by istar** [xiewenwei/redis_scanner#2]
.rvm/gems/ruby-2.2.2/gems/redis_scanner-0.1.4/lib/redis_scanner/rule.rb:18:in `match': invalid byte sequence in US-ASCII (ArgumentError)･････････････････････ 0% Keys
    from /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/redis_scanner-0.1.4/lib/redis_scanner/rule.rb:18:in`block in extract_pattern'
    from /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/redis_scanner-0.1.4/lib/redis_scanner/rule.rb:17:in `each'
    from /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/redis_scanner-0.1.4/lib/redis_scanner/rule.rb:17:in`extract_pattern'
    from /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/redis_scanner-0.1.4/lib/redis_scanner/engine.rb:42:in `block in scan'
    from /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/redis_scanner-0.1.4/lib/redis_scanner/engine.rb:41:in`each'
    from /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/redis_scanner-0.1.4/lib/redis_scanner/engine.rb:41:in `scan'
    from /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/redis_scanner-0.1.4/lib/redis_scanner/engine.rb:12:in`run'
    from /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/redis_scanner-0.1.4/lib/redis_scanner.rb:13:in `scan'
    from /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/redis_scanner-0.1.4/bin/redis_scanner:64:in`<top (required)>'
    from /home/ec2-user/.rvm/gems/ruby-2.2.2/bin/redis_scanner:23:in `load'
    from /home/ec2-user/.rvm/gems/ruby-2.2.2/bin/redis_scanner:23:in`<main>'
    from /home/ec2-user/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
    from /home/ec2-user/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in`<main>'

**Comment by xiewenwei** [comment]
It crashed because some key included invalid byte sequence and there was no fault-tolerance.
I have fixed it in the latest master branch.
